// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9JNxGbrXZiO4D5jktzwlXfFBYm9eFi28',
    appId: '1:496304352751:web:ad3618f1d92fc44b72da1a',
    messagingSenderId: '496304352751',
    projectId: 'dig-it-kttn',
    authDomain: 'dig-it-kttn.firebaseapp.com',
    storageBucket: 'dig-it-kttn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsi_1ZxfSx8fmB86Pyoa-4HchDS0wfToI',
    appId: '1:496304352751:android:2b26ee64156714bd72da1a',
    messagingSenderId: '496304352751',
    projectId: 'dig-it-kttn',
    storageBucket: 'dig-it-kttn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW-vfK4YzV4HOX8E8sKs2MgaAZFzd4uQ',
    appId: '1:496304352751:ios:46a43e1c064cd23b72da1a',
    messagingSenderId: '496304352751',
    projectId: 'dig-it-kttn',
    storageBucket: 'dig-it-kttn.firebasestorage.app',
    iosBundleId: 'com.example.digitKttn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpW-vfK4YzV4HOX8E8sKs2MgaAZFzd4uQ',
    appId: '1:496304352751:ios:46a43e1c064cd23b72da1a',
    messagingSenderId: '496304352751',
    projectId: 'dig-it-kttn',
    storageBucket: 'dig-it-kttn.firebasestorage.app',
    iosBundleId: 'com.example.digitKttn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9JNxGbrXZiO4D5jktzwlXfFBYm9eFi28',
    appId: '1:496304352751:web:7d087c9cee42ff6572da1a',
    messagingSenderId: '496304352751',
    projectId: 'dig-it-kttn',
    authDomain: 'dig-it-kttn.firebaseapp.com',
    storageBucket: 'dig-it-kttn.firebasestorage.app',
  );
}
